### ISSUE TITLE
Error Arrow - attempt to perform arithmetic on upvalue 'targetX' (a nil value)

### ISSUE THREAD

**Issue by Imna1975** [Kirri777/WorldQuestsList#13]
924x WorldQuestsList/Arrow.lua:262: attempt to perform arithmetic on upvalue 'targetX' (a nil value)
[string "@WorldQuestsList/Arrow.lua"]:262: in function <WorldQuestsList/Arrow.lua:234>

Locals:
self = Button {
 0 = <userdata>
 PixelSnapDisabled = true
}
elapsed = 0.028000
y = 1452.800049
x = -276
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = 0
(*temporary) = 2444
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on upvalue 'targetX' (a nil value)"
hideTime = nil
GetTime = <function> defined =[C]:-1
currWaypoint = nil
frame = Button {
 0 = <userdata>
 PixelSnapDisabled = true
}
UnitPosition = <function> defined =[C]:-1
targetType = "fixed"
targetY = nil
targetX = nil
targetPlayer = nil
rotateState = 0
cos = <function> defined =[C]:-1
sin = <function> defined =[C]:-1
atan2 = <function> defined =[C]:-1
runAwayArrow = false
pi = 3.141593
pi2 = 6.283185
GetPlayerFacing = <function> defined @WorldQuestsList/Arrow.lua:27
updateArrow = <function> defined @WorldQuestsList/Arrow.lua:100
sqrt = <function> defined =[C]:-1

**Comment by Kirri777** [comment]
How can I get this error?
